#!/usr/bin/env bash

              #@@@@@@@^^~~~~~~~~~~~~~~~~~~~~^@@@@@@@@@#
              #@@@@@@^     ~^  @  @@ @ @ @ I  ~^@@@@@@#
              #@@@@@            ~ ~~ ~I          @@@@@#
              #@@@@'                  '  _,w@<    @@@@#
              #@@@@     @@@@@@@@w___,w@@@@@@@@  @  @@@#
              #@@@@     @@@@@@@@@@@@@@@@@@@@@@  I  @@@#
              #@@@@     @@@@@@@@@@@@@@@@@@@@*@[ i  @@@#
              #@@@@     @@@@@@@@@@@@@@@@@@@@[][ | ]@@@#
              #@@@@     ~_,,_ ~@@@@@@@~ ____~ @    @@@#
              #@@@@    _~ ,  ,  `@@@~  _  _`@ ]L  J@@@#
              #@@@@  , @@w@ww+   @@@ww``,,@w@ ][  @@@@#
              #@@@@,  @@@@www@@@ @@@@@@@ww@@@@@[  @@@@#
              #@@@@@_|| @@@@@@P' @@P@@@@@@@@@@@[|c@@@@#
              #@@@@@@w| '@@P~  P]@@@-~, ~Y@@^'],@@@@@@#
              #@@@@@@@[   _        _J@@Tk     ]]@@@@@@#
              #@@@@@@@@,@ @@, c,,,,,,,y ,w@@[ ,@@@@@@@#
              #@@@@@@@@@ i @w   ====--_@@@@@  @@@@@@@@#
              #@@@@@@@@@@`,P~ _ ~^^^^Y@@@@@  @@@@@@@@@#
              #@@@@^^=^@@^   ^' ,ww,w@@@@@ _@@@@@@@@@@#
              #@@@_xJ~ ~   ,    @@@@@@@P~_@@@@@@@@@@@@#
              #@@   @,   ,@@@,_____   _,J@@@@@@@@@@@@@#
              #@@L  `' ,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
              #@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#

set -e  # Exit immediately if a command fails

# ====== PATH VARIABLES ======
mrk1_dir=$HOME/mrk1                  # Base directory for mrk1 project
scripts=$mrk1_dir/scripts       # Location of project-specific scripts

bin=$HOME/.local/bin                 # User-specific binaries

backup=$scripts/backup.sh
restore=$scripts/restore.sh
syncall=$scripts/syncall.sh
brewfile=$mrk1_dir/Brewfile

echo "Creating script symlinks in .local/bin directory"
for file in $scripts/{backup,restore,syncall}; do
    if [ -r "$file" ] && [ -f "$file" ]; then
        ln -sf "$file" $bin || { echo "Error symlinking $file"; exit 1; }
    else
        echo "Skipping $file: Not a regular file or not readable"
    fi
done
