#!/usr/bin/env bash

# Color variables for better readability
bold=$(tput bold)
yellow=$(tput setaf 3)
reset=$(tput sgr0)
green=$(tput setaf 2)  # Corrected color variable for green

# Function to print arrows for better visual separation
arrow() {
    echo
    echo "${green}${bold}>>> ${reset}$*"
}

#-------------------------------------------------------------------------------
echo "Running restore script"
sleep 1

#-------------------------------------------------------------------------------
arrow "Restoring to ${yellow}~/Library/Saved Application State${reset}" && echo
sleep 1

sudo rsync -av ~/.backups/Saved\ Application\ State/ ~/Library/Saved\ Application\ State/

#-------------------------------------------------------------------------------
arrow "Restoring ${yellow}~/Library/Preferences${reset}" && echo
sleep 1

sudo rsync -av ~/.backups/Preferences/ ~/Library/Preferences/

#-------------------------------------------------------------------------------
arrow "Restoring ${yellow}~/Music/Audio Music Apps${reset}" && echo
sleep 1

sudo rsync -av ~/.backups/Audio\ Music\ Apps/ ~/Music/Audio\ Music\ Apps/

#-------------------------------------------------------------------------------
arrow "Restoring ${yellow}~/Documents/iZotope${reset}" && echo
sleep 1

sudo rsync -av ~/.backups/iZotope ~/Documents/iZotope/

#-------------------------------------------------------------------------------
echo "Restore Chrono Plus data manually"
sleep 1

#-------------------------------------------------------------------------------
echo ""
echo "${yellow}–––––––––––––––––––––––––––${reset}"
echo "     Restore successful"
echo "${yellow}–––––––––––––––––––––––––––${reset}"
