#!/usr/bin/env bash

#____________________//Personal sync script for//______________________________#
#______      ______                                           _           _____#
#_____      / ____ \________ _   ______ ___  ____  __________(_)____       ____#
#____      / / __ `/ ___/ _ \ | / / __ `__ \/ __ \/ ___/ ___/ / ___/      _____#
#___      / / /_/ (__  )  __/ |/ / / / / / / /_/ / /  / /  / (__  )      ______#
#____     \ \__,_/____/\___/|___/_/ /_/ /_/\____/_/  /_/  /_/____/      _______#
#_____     \____/                                                      ________#
#______________________________________________________________________________#

# Constants for color output
bold=$(tput bold)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
cyan=$(tput setaf 6)
reset=$(tput sgr0)

# Function for pushing changes to GitHub
push_to_github() {
  local repo_dir="$1"
  local commit_message="${2:-$(date '+%y%m%d-%H%M')}" # Optional message

  # Change directory and exit if it fails
  cd "$repo_dir" || return 1

  echo
  echo "${cyan}${bold}Pushing changes to GitHub: $repo_dir${reset}"
  git pull
  git add .
  git commit -m "$commit_message"
  git push
  echo "${green}${bold}Changes pushed to GitHub${reset}"
}

# Constants and descriptive variable names
dotfiles_dir="$HOME/mrk1/dotfiles"
brewfile_source="$HOME/mrk1/assets/Brewfile"
backups="$HOME/.backups"

# Sync Brewfile
echo
echo "${cyan}${bold}Syncing ${brewfile_source} to $HOME${reset}"
rsync -rtu --progress "$brewfile_source" "$HOME"
echo "${green}${bold}Synced ${brewfile_source} to $HOME${reset}"
sleep 2

# Push changes to GitHub (using the function)
push_to_github "$HOME/mrk1" "$backups"

# Success message and logging
echo
echo "${green}––––––––––––––${reset}"
echo "${cyan}${bold}Sync complete${reset}"
echo "syncall $(date +"%y%m%d %r")" >> ~/Library/Logs/mrk1-backups.log
echo "${green}––––––––––––––${reset}"
echo
